[alpha-software]
icon = "flask"
title.en = "Alpha software"
title.fr = "Logiciel en version alpha"
description.en = "⚠️ PLEASE READ CAREFULLY ⚠️

Sharkey requires redis version 7, but YunoHost does not currently support this version.
Some functions will not be available if you install this package.

I advise you to wait for the release of Bookworm Debian 12."
description.fr = "⚠️ A LIRE ATTENTIVEMENT ⚠️

Attention Sharkey nécessite la version 7 de redis hors YunoHost ne permet pas actuellement de bénéficier de cette version.
Certaines fonctions ne seront pas disponible si vous installez ce package.

Je vous conseille d'attendre la sortie de Bookworm Debian 12"
