packaging_format = 2

id = "sharkey"
name = "Sharkey"
description.en = "Microblogging platform"
description.fr = "Platforme de Microblogging"

version = "2024.9.3~ynh1"

maintainers = ["oufmilo"]

[upstream]
license = "AGPL-3.0"
website = "https://git.joinsharkey.org/Sharkey"
code = "https://activitypub.software/TransFem-org/Sharkey"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "If enabled, Misskey will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Misskey sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]

    [resources.sources.main]
    url = "https://activitypub.software/TransFem-org/Sharkey/-/archive/2024.9.3/Sharkey-2024.9.3.tar.bz2"
    sha256 = "59fede411dc4d7a4d4eb3ddbbf527bf6dc159ad9f20aa83a9916b79324a75e4b"

    autoupdate.strategy = "latest_gitlab_release"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages ="ffmpeg, postgresql, git, build-essential, redis-server"

    [resources.database]
    type = "postgresql"
