test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

      exclude = ["change_url"]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.7e1b7fc.name = "2023.12.0"