test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

      exclude = ["change_url"]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.ce8f3365661567ea5f23168b785a5d290a0bcf38.name = "2023.12.1"